# -*- coding: utf-8 -*-
"""Task1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vALyoD2f86zsJQbiEeRYYJZm_Kcp5GYX
"""

import random
import numpy as np
class RandomGen(object):
    # Values that may be returned by next_num()
    _random_nums = [-1, 0, 1, 2, 3]
    # Probability of the occurence of random_nums
    _probabilities = [0.01, 0.3, 0.58, 0.1, 0.01]
    def next_num(self):
        return random.choices(self._random_nums, self._probabilities)
        
RandomGen().next_num()

